### PR TITLE
Edit some sentence

### PR DESCRIPTION
**Pull request by youngmtool**

### CODE REVIEW

**Comment by knocte** [comment]
@nopara73 @youngmtool I agree with the changes here, except this one:

-*   You enumerate how much **Money** you want to send to what **scriptPubKey**,
+*   You enumerate how much **Money** you want to send to what **scriptPubKey** indicates,

to what scriptPubKey indicates? that doesn't sound right to me.

**Comment by youngmtool** [comment]
Thanks for the review and comment.
I wanted to mean a recipient for the coin in a TxOut of a transaction.
Is it wrong?

**Comment by nopara73** [comment]
@knocte is 100% right. I fixed it: https://github.com/ProgrammingBlockchain/ProgrammingBlockchain/commit/41b688348b1aa0b3265d65eb6c92b1b24e8b2ce9  

> I wanted to mean a recipient for the coin in a TxOut of a transaction.  

The scriptPubKey is the recipient. See Mastering Bitcoin: https://github.com/bitcoinbook/bitcoinbook/blob/second_edition/ch06.asciidoc#script-construction-lock--unlock

> A locking script is a spending condition placed on an output: it specifies the conditions that must be met to spend the output in the future. Historically, the locking script was called a scriptPubKey, because it usually contained a public key or bitcoin address (public key hash). In this book we refer to it as a "locking script" to acknowledge the much broader range of possibilities of this scripting technology. In most bitcoin applications, what we refer to as a locking script will appear in the source code as scriptPubKey. You will also see the locking script referred to as a witness script (see [segwit]) or more generally as a cryptographic puzzle. These terms all mean the same thing, at different levels of abstraction.

**Comment by youngmtool** [comment]
Thanks for correction and references. But doesn't it make sense in English grammar? Does it need another verb?

**Comment by nopara73** [comment]
@knocte ? I personally don't see any problem with that sentence, though I'm not a native Enlglish speaker, so don't mind me.

**Comment by knocte** [comment]
Not a native English speaker here either, but @youngmtool if you think the sentence makes more sense with that "indicates" word at the end, I think you're not understanding the sentence.

**Comment by youngmtool** [comment]
I'm not a native English speaker, either. According to my understanding of a ScriptPubKey at the moment, and reference which @nopara73 wrote, I cannot help but consider a ScriptPubKey as a recipient to which the coins will be sent. 
I may have had wrong or lack concepts in some parts.
What's the wrong part from the statement I wrote from above?
What verb do you think fits in there?

**Comment by knocte** [comment]
I don't think a verb is needed. Please read again the text before the list starts, and then the sentence in that list item. It's clear to me.

**Comment by youngmtool** [comment]
The usage of the builder is done in four steps:
You gather the Coins that spent,
You gather the Keys that you own,
You enumerate how much Money you want to send to what scriptPubKey,
You build and sign the transaction,
Optional: you give the transaction to somebody else, then he will sign or continue to build it.

This is what I'm seeing.
I think I may look at this in 2 ways.

1.
send to what scriptPubKey, You build and sign the transaction,
The case that all sentences for four steps are in a row.
But for me, it doesn't make sense in meaning and grammar.

2.
When I look at this sentence, You enumerate how much Money you want to send to what scriptPubKey, as a one sentence,
I read like this:
You / enumerate / how much Money / you want to send to / what scriptPubKey,
So I felt the following sentence more appropriate in meaning and grammar:
You / enumerate / how much Money / you want to send to / what scriptPubKey indicates,

Anyway, since I don't know well, I think I'd better to pass it. Thanks for the feedback.

**Pull request merged**
