### PR TITLE
Recommend Atom editor for extensive contribution

### PR DESCRIPTION
**Pull request by hypergori**
Recommend Atom editor for extensive contribution until Gitbook client gets better.
Mention how to do the inline comment

### CODE REVIEW

**Comment by nopara73** [comment]
GitBook is for people who are not familiar with Markdown and Git and GitHub. Atom as far as now does not attempt to overcome any of those issues. Am I right?  
If so maybe we should explicitly state our GitBook recommendation only for those who are not familiar with the above mentioned technologies and add if you are familiar then you'd be better off with Atom, Notepad++, Visual Studio Code or something ligthweight IDE.

**Comment by hypergori** [comment]
OK. Let me change it to cover both groups  ,the git-markdown literate and git-markdown illiterate.

**Comment by NicolasDorier** [comment]
yeah I think both should be present.

**Comment by nopara73** [comment]
Merged it. By the way we got the criticism of the past that our readme.md shouldn't be contributing.md. This will not help on that:)

**Pull request merged**
