### PR TITLE
Update example Network Provider constructor

### PR DESCRIPTION
**Pull request by bitcoinbrisbane**
I think this is the correct way now.

### CODE REVIEW

**Comment by nopara73** [comment]
image

**Comment by bitcoinbrisbane** [comment]
oh :(

**Comment by NicolasDorier** [comment]
nice try :p

**Comment by bitcoinbrisbane** [comment]
Ok, I guess I’m missing something

**Comment by NicolasDorier** [comment]
the `GetBCH` was not a troll?

**Comment by bitcoinbrisbane** [comment]
Haha no! I didn’t even notice. I’ve got a BCH client, I couldn’t find the chain type object and had to use the Network Type

**Comment by NicolasDorier** [comment]
ah so can you make another PR without the GetBCH? :D

**Comment by bitcoinbrisbane** [comment]
> ah so can you make another PR without the GetBCH? :D

Done.

**Comment by nopara73** [comment]
Thank you!

**Pull request merged**
