### PR TITLE
Update web-api.md

### PR DESCRIPTION
**Pull request by walkjivefly**
typos

### CODE REVIEW

**Comment by nopara73** [comment]
I'm fine with both naming. @NicolasDorier merge or close?

**Comment by nopara73** [comment]
Wait, I don't understand when I look at the diff of this PR, there's no naming change. But when I look at only your last commit, I see the naming change: https://github.com/ProgrammingBlockchain/ProgrammingBlockchain/pull/126/commits/4daba8a677979978270627ef8e238122aa1168ab  

I'm confused.

**Comment by walkjivefly** [comment]
Sorry, I don't understand the question. Naming change? 

Did I do something wrong in the workflow? I changed a bunch of typos in the first commit and then expanded a couple of the altcoin names (to avoid any cofusion) in a second commit. Won't the merge pickup both?

**Comment by nopara73** [comment]
If I click on the commit it shows this:

image

If I click on the diff of the PR it shows this (last commit diff is missing):

image

**Comment by NicolasDorier** [comment]
BCash and BGold seems better to me though.

**Comment by walkjivefly** [comment]
I changed the names back to BCash and BGold. 
There were 2 choices at the end: commit to patch-3 branch or create a new branch and open a new PR. I chose the first one.

**Pull request merged**
