### PR TITLE
translate to korean language

### PR DESCRIPTION
**Pull request by lisa3907**
한국어 번역 작업을 시작 했습니다. 한 찹터씩 시간 될때 마다 번역 작업을 하고자 합니다.
I started working on a Korean translation. I would like to work on a translation whenever I have time, one by one.

### CODE REVIEW

**Comment by nopara73** [comment]
Thanks @lisa3907! If you think you got to a reasonable state with the translation, we'll create a repo for it as we did with other translations: https://github.com/ProgrammingBlockchain

**Comment by lisa3907** [comment]
> Thanks @lisa3907! If you think you got to a reasonable state with the translation, we'll create a repo for it as we did with other translations: https://github.com/ProgrammingBlockchain

What is the evaluation method for reaching a reasonable state?

**Comment by nopara73** [comment]
For me, one chapter (not the introduction though:)

Other maintainers may disagree though.

**Comment by NicolasDorier** [comment]
Created https://github.com/ProgrammingBlockchain/ProgrammingBlockchain-Korean and added you as admin.

**Comment by lisa3907** [comment]
> Created https://github.com/ProgrammingBlockchain/ProgrammingBlockchain-Korean and added you as admin.

Thank you!! 감사합니다.

**Comment by nopara73** [comment]
감사합니다

**Pull request closed without merging**
