### PR TITLE
translate to Indonesian Language

### PR DESCRIPTION
**Pull request by eb-ina**

### CODE REVIEW

**Comment by NicolasDorier** [comment]
@eb-ina why closed ? :(

**Comment by nopara73** [comment]
Awesome work! Thank you so much! We have no strategy  of how to handle translations just yet, but we will shortly figure it out :+1:

**Comment by NicolasDorier** [comment]
I think this should be in its own repo with @eb-ina having commit access.

**Comment by nopara73** [comment]
Yes, own repo it is, we will link to it. @eb-ina could you please prepare it?

**Comment by NicolasDorier** [comment]
@eb-ina, I created the repo for you, you have rights on it.
https://github.com/ProgrammingBlockchain/ProgrammingBlockchain-Indonesian/

**Comment by nopara73** [comment]
I configured properly the [GitHub](https://github.com/ProgrammingBlockchain/ProgrammingBlockchain-Indonesian/) and [GitBook](https://www.gitbook.com/book/nopara73/programmingblockchainindonesian) repo.  
Also added [Other languages section](https://github.com/ProgrammingBlockchain/ProgrammingBlockchain#other-languages) to the README.md.  
  
Here is how it works in a nutshell:  
Modifications are on GitHub, GitBook catches all the changes and makes them readable.  
GitBook editor also modifies the GitHub repository, not GitBook, (I suppose you were using that.)  
  
@eb-ina if you would not like to maintain the Indonesian repo, it's fine.  
If you would like to then just do as it is most comfortable to you.  
If you find git-github-gitbook confusing, here is a simple way to do it:  
1. Clone the Indonesian GitHub repo.  
2. Clone the English GitHub repo.  
3. Whenever a change happens in the English repo, update it in the Indonesian repo, then commit and push.  
(There might be better magic git ways to keep it up-to-date I am not aware of.)

**Comment by nopara73** [comment]
I shared it on a few places:  
[Reddit](https://www.reddit.com/r/Bitcoin/comments/4wzbt6/unexpectedly_someone_just_created_a_pull_request/)
[Twitter](https://twitter.com/nopara73/status/763160577682182144)
[Bitcointalk](https://bitcointalk.org/index.php?topic=1580855.0)

**Pull request closed without merging**
